# Generated by Django 5.0.6 on 2024-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
